// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MigrationAnalysing.DataAccess;

#nullable disable

namespace MigrationAnalysing.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251017095526_Table18Migration14")]
    partial class Table18Migration14
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MigrationAnalysing.Models.Table1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("column1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column10")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column11")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column12")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column13")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column14")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column15")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column16")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column17")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column18")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column19")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column20")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column21")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column22")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column23")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column24")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column9")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Table1");
                });

            modelBuilder.Entity("MigrationAnalysing.Models.Table10", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("column1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column10")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column11")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column12")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column13")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column14")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column15")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column16")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column17")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column18")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column19")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column20")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column21")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column22")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column23")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column24")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column9")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Table10");
                });

            modelBuilder.Entity("MigrationAnalysing.Models.Table11", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("column1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column10")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column11")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column12")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column13")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column14")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column15")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column16")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column17")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column18")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column19")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column20")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column21")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column22")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column23")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column24")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column9")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Table11");
                });

            modelBuilder.Entity("MigrationAnalysing.Models.Table12", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("column1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column10")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column11")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column12")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column13")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column14")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column15")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column16")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column17")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column18")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column19")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column20")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column21")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column22")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column23")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column24")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column9")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Table12");
                });

            modelBuilder.Entity("MigrationAnalysing.Models.Table13", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("column1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column10")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column11")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column12")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column13")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column14")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column15")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column16")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column17")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column18")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column19")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column20")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column21")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column22")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column23")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column24")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column9")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Table13");
                });

            modelBuilder.Entity("MigrationAnalysing.Models.Table14", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("column1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column10")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column11")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column12")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column13")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column14")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column15")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column16")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column17")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column18")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column19")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column20")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column21")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column22")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column23")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column24")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column9")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Table14");
                });

            modelBuilder.Entity("MigrationAnalysing.Models.Table15", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("column1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column10")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column11")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column12")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column13")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column14")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column15")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column16")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column17")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column18")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column19")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column20")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column21")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column22")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column23")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column24")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column9")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Table15");
                });

            modelBuilder.Entity("MigrationAnalysing.Models.Table16", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("column1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column10")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column11")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column12")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column13")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column14")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column15")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column16")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column17")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column18")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column19")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column20")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column21")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column22")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column23")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column24")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column9")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Table16");
                });

            modelBuilder.Entity("MigrationAnalysing.Models.Table17", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("column1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column10")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column11")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column12")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column13")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column14")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column15")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column16")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column17")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column18")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column19")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column20")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column21")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column22")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column23")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column24")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column9")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Table17");
                });

            modelBuilder.Entity("MigrationAnalysing.Models.Table18", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("column1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column10")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column11")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column12")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column13")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column14")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column9")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Table18");
                });

            modelBuilder.Entity("MigrationAnalysing.Models.Table19", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("column1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column9")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Table19");
                });

            modelBuilder.Entity("MigrationAnalysing.Models.Table2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("column1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column10")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column11")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column12")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column13")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column14")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column15")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column16")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column17")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column18")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column19")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column20")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column21")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column22")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column23")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column24")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column9")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Table2");
                });

            modelBuilder.Entity("MigrationAnalysing.Models.Table20", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("column1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column9")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Table20");
                });

            modelBuilder.Entity("MigrationAnalysing.Models.Table3", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("column1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column10")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column11")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column12")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column13")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column14")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column15")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column16")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column17")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column18")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column19")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column20")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column21")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column22")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column23")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column24")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column9")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Table3");
                });

            modelBuilder.Entity("MigrationAnalysing.Models.Table4", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("column1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column10")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column11")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column12")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column13")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column14")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column15")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column16")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column17")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column18")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column19")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column20")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column21")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column22")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column23")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column24")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column9")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Table4");
                });

            modelBuilder.Entity("MigrationAnalysing.Models.Table5", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("column1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column10")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column11")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column12")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column13")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column14")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column15")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column16")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column17")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column18")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column19")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column20")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column21")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column22")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column23")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column24")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column9")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Table5");
                });

            modelBuilder.Entity("MigrationAnalysing.Models.Table6", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("column1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column10")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column11")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column12")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column13")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column14")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column15")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column16")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column17")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column18")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column19")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column20")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column21")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column22")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column23")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column24")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column9")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Table6");
                });

            modelBuilder.Entity("MigrationAnalysing.Models.Table7", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("column1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column10")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column11")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column12")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column13")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column14")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column15")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column16")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column17")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column18")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column19")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column20")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column21")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column22")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column23")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column24")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column9")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Table7");
                });

            modelBuilder.Entity("MigrationAnalysing.Models.Table8", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("column1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column10")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column11")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column12")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column13")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column14")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column15")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column16")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column17")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column18")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column19")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column20")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column21")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column22")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column23")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column24")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column9")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Table8");
                });

            modelBuilder.Entity("MigrationAnalysing.Models.Table9", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("column1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column10")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column11")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column12")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column13")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column14")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column15")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column16")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column17")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column18")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column19")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column20")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column21")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column22")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column23")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column24")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column9")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Table9");
                });
#pragma warning restore 612, 618
        }
    }
}
