// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MigrationAnalysing.DataAccess;

#nullable disable

namespace MigrationAnalysing.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251015101401_Table6Migration2")]
    partial class Table6Migration2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MigrationAnalysing.Models.Table1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("column1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column9")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Table1");
                });

            modelBuilder.Entity("MigrationAnalysing.Models.Table2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("column1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column9")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Table2");
                });

            modelBuilder.Entity("MigrationAnalysing.Models.Table3", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("column1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column9")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Table3");
                });

            modelBuilder.Entity("MigrationAnalysing.Models.Table4", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("column1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column9")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Table4");
                });

            modelBuilder.Entity("MigrationAnalysing.Models.Table5", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("column1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column9")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Table5");
                });

            modelBuilder.Entity("MigrationAnalysing.Models.Table6", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("column1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("column2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Table6");
                });
#pragma warning restore 612, 618
        }
    }
}
