// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace MigrationAnalysing
{
    public partial class AppDbContextModel
    {
        private AppDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("9c37b278-2dfc-4cc9-9209-09b5e900fe9e"), entityTypeCount: 20)
        {
        }

        partial void Initialize()
        {
            var table1 = Table1EntityType.Create(this);
            var table10 = Table10EntityType.Create(this);
            var table11 = Table11EntityType.Create(this);
            var table12 = Table12EntityType.Create(this);
            var table13 = Table13EntityType.Create(this);
            var table14 = Table14EntityType.Create(this);
            var table15 = Table15EntityType.Create(this);
            var table16 = Table16EntityType.Create(this);
            var table17 = Table17EntityType.Create(this);
            var table18 = Table18EntityType.Create(this);
            var table19 = Table19EntityType.Create(this);
            var table2 = Table2EntityType.Create(this);
            var table20 = Table20EntityType.Create(this);
            var table3 = Table3EntityType.Create(this);
            var table4 = Table4EntityType.Create(this);
            var table5 = Table5EntityType.Create(this);
            var table6 = Table6EntityType.Create(this);
            var table7 = Table7EntityType.Create(this);
            var table8 = Table8EntityType.Create(this);
            var table9 = Table9EntityType.Create(this);

            Table1EntityType.CreateAnnotations(table1);
            Table10EntityType.CreateAnnotations(table10);
            Table11EntityType.CreateAnnotations(table11);
            Table12EntityType.CreateAnnotations(table12);
            Table13EntityType.CreateAnnotations(table13);
            Table14EntityType.CreateAnnotations(table14);
            Table15EntityType.CreateAnnotations(table15);
            Table16EntityType.CreateAnnotations(table16);
            Table17EntityType.CreateAnnotations(table17);
            Table18EntityType.CreateAnnotations(table18);
            Table19EntityType.CreateAnnotations(table19);
            Table2EntityType.CreateAnnotations(table2);
            Table20EntityType.CreateAnnotations(table20);
            Table3EntityType.CreateAnnotations(table3);
            Table4EntityType.CreateAnnotations(table4);
            Table5EntityType.CreateAnnotations(table5);
            Table6EntityType.CreateAnnotations(table6);
            Table7EntityType.CreateAnnotations(table7);
            Table8EntityType.CreateAnnotations(table8);
            Table9EntityType.CreateAnnotations(table9);

            AddAnnotation("ProductVersion", "9.0.10");
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
        }
    }
}
