// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace MigrationAnalysing
{
    public partial class AppDbContextModel
    {
        private AppDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("16216a64-8eda-465b-b2bd-1575531e342a"), entityTypeCount: 10)
        {
        }

        partial void Initialize()
        {
            var table1 = Table1EntityType.Create(this);
            var table10 = Table10EntityType.Create(this);
            var table2 = Table2EntityType.Create(this);
            var table3 = Table3EntityType.Create(this);
            var table4 = Table4EntityType.Create(this);
            var table5 = Table5EntityType.Create(this);
            var table6 = Table6EntityType.Create(this);
            var table7 = Table7EntityType.Create(this);
            var table8 = Table8EntityType.Create(this);
            var table9 = Table9EntityType.Create(this);

            Table1EntityType.CreateAnnotations(table1);
            Table10EntityType.CreateAnnotations(table10);
            Table2EntityType.CreateAnnotations(table2);
            Table3EntityType.CreateAnnotations(table3);
            Table4EntityType.CreateAnnotations(table4);
            Table5EntityType.CreateAnnotations(table5);
            Table6EntityType.CreateAnnotations(table6);
            Table7EntityType.CreateAnnotations(table7);
            Table8EntityType.CreateAnnotations(table8);
            Table9EntityType.CreateAnnotations(table9);

            AddAnnotation("ProductVersion", "9.0.10");
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
        }
    }
}
