// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using MigrationAnalysing;
using MigrationAnalysing.DataAccess;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(AppDbContext), typeof(AppDbContextModel))]
