// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using MigrationAnalysing.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace MigrationAnalysing
{
    [EntityFrameworkInternal]
    public partial class Table6EntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "MigrationAnalysing.Models.Table6",
                typeof(Table6),
                baseEntityType,
                propertyCount: 50,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(int),
                propertyInfo: typeof(Table6).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Table6).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            id.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            var column1 = runtimeEntityType.AddProperty(
                "column1",
                typeof(string),
                propertyInfo: typeof(Table6).GetProperty("column1", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Table6).GetField("<column1>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            column1.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var column10 = runtimeEntityType.AddProperty(
                "column10",
                typeof(string),
                propertyInfo: typeof(Table6).GetProperty("column10", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Table6).GetField("<column10>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            column10.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var column11 = runtimeEntityType.AddProperty(
                "column11",
                typeof(string),
                propertyInfo: typeof(Table6).GetProperty("column11", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Table6).GetField("<column11>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            column11.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var column12 = runtimeEntityType.AddProperty(
                "column12",
                typeof(string),
                propertyInfo: typeof(Table6).GetProperty("column12", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Table6).GetField("<column12>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            column12.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var column13 = runtimeEntityType.AddProperty(
                "column13",
                typeof(string),
                propertyInfo: typeof(Table6).GetProperty("column13", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Table6).GetField("<column13>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            column13.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var column14 = runtimeEntityType.AddProperty(
                "column14",
                typeof(string),
                propertyInfo: typeof(Table6).GetProperty("column14", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Table6).GetField("<column14>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            column14.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var column15 = runtimeEntityType.AddProperty(
                "column15",
                typeof(string),
                propertyInfo: typeof(Table6).GetProperty("column15", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Table6).GetField("<column15>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            column15.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var column16 = runtimeEntityType.AddProperty(
                "column16",
                typeof(string),
                propertyInfo: typeof(Table6).GetProperty("column16", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Table6).GetField("<column16>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            column16.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var column17 = runtimeEntityType.AddProperty(
                "column17",
                typeof(string),
                propertyInfo: typeof(Table6).GetProperty("column17", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Table6).GetField("<column17>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            column17.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var column18 = runtimeEntityType.AddProperty(
                "column18",
                typeof(string),
                propertyInfo: typeof(Table6).GetProperty("column18", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Table6).GetField("<column18>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            column18.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var column19 = runtimeEntityType.AddProperty(
                "column19",
                typeof(string),
                propertyInfo: typeof(Table6).GetProperty("column19", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Table6).GetField("<column19>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            column19.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var column2 = runtimeEntityType.AddProperty(
                "column2",
                typeof(string),
                propertyInfo: typeof(Table6).GetProperty("column2", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Table6).GetField("<column2>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            column2.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var column20 = runtimeEntityType.AddProperty(
                "column20",
                typeof(string),
                propertyInfo: typeof(Table6).GetProperty("column20", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Table6).GetField("<column20>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            column20.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var column21 = runtimeEntityType.AddProperty(
                "column21",
                typeof(string),
                propertyInfo: typeof(Table6).GetProperty("column21", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Table6).GetField("<column21>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            column21.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var column22 = runtimeEntityType.AddProperty(
                "column22",
                typeof(string),
                propertyInfo: typeof(Table6).GetProperty("column22", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Table6).GetField("<column22>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            column22.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var column23 = runtimeEntityType.AddProperty(
                "column23",
                typeof(string),
                propertyInfo: typeof(Table6).GetProperty("column23", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Table6).GetField("<column23>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            column23.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var column24 = runtimeEntityType.AddProperty(
                "column24",
                typeof(string),
                propertyInfo: typeof(Table6).GetProperty("column24", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Table6).GetField("<column24>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            column24.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var column25 = runtimeEntityType.AddProperty(
                "column25",
                typeof(string),
                propertyInfo: typeof(Table6).GetProperty("column25", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Table6).GetField("<column25>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            column25.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var column26 = runtimeEntityType.AddProperty(
                "column26",
                typeof(string),
                propertyInfo: typeof(Table6).GetProperty("column26", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Table6).GetField("<column26>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            column26.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var column27 = runtimeEntityType.AddProperty(
                "column27",
                typeof(string),
                propertyInfo: typeof(Table6).GetProperty("column27", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Table6).GetField("<column27>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            column27.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var column28 = runtimeEntityType.AddProperty(
                "column28",
                typeof(string),
                propertyInfo: typeof(Table6).GetProperty("column28", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Table6).GetField("<column28>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            column28.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var column29 = runtimeEntityType.AddProperty(
                "column29",
                typeof(string),
                propertyInfo: typeof(Table6).GetProperty("column29", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Table6).GetField("<column29>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            column29.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var column3 = runtimeEntityType.AddProperty(
                "column3",
                typeof(string),
                propertyInfo: typeof(Table6).GetProperty("column3", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Table6).GetField("<column3>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            column3.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var column30 = runtimeEntityType.AddProperty(
                "column30",
                typeof(string),
                propertyInfo: typeof(Table6).GetProperty("column30", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Table6).GetField("<column30>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            column30.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var column31 = runtimeEntityType.AddProperty(
                "column31",
                typeof(string),
                propertyInfo: typeof(Table6).GetProperty("column31", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Table6).GetField("<column31>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            column31.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var column32 = runtimeEntityType.AddProperty(
                "column32",
                typeof(string),
                propertyInfo: typeof(Table6).GetProperty("column32", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Table6).GetField("<column32>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            column32.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var column33 = runtimeEntityType.AddProperty(
                "column33",
                typeof(string),
                propertyInfo: typeof(Table6).GetProperty("column33", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Table6).GetField("<column33>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            column33.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var column34 = runtimeEntityType.AddProperty(
                "column34",
                typeof(string),
                propertyInfo: typeof(Table6).GetProperty("column34", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Table6).GetField("<column34>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            column34.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var column35 = runtimeEntityType.AddProperty(
                "column35",
                typeof(string),
                propertyInfo: typeof(Table6).GetProperty("column35", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Table6).GetField("<column35>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            column35.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var column36 = runtimeEntityType.AddProperty(
                "column36",
                typeof(string),
                propertyInfo: typeof(Table6).GetProperty("column36", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Table6).GetField("<column36>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            column36.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var column37 = runtimeEntityType.AddProperty(
                "column37",
                typeof(string),
                propertyInfo: typeof(Table6).GetProperty("column37", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Table6).GetField("<column37>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            column37.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var column38 = runtimeEntityType.AddProperty(
                "column38",
                typeof(string),
                propertyInfo: typeof(Table6).GetProperty("column38", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Table6).GetField("<column38>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            column38.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var column39 = runtimeEntityType.AddProperty(
                "column39",
                typeof(string),
                propertyInfo: typeof(Table6).GetProperty("column39", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Table6).GetField("<column39>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            column39.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var column4 = runtimeEntityType.AddProperty(
                "column4",
                typeof(string),
                propertyInfo: typeof(Table6).GetProperty("column4", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Table6).GetField("<column4>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            column4.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var column40 = runtimeEntityType.AddProperty(
                "column40",
                typeof(string),
                propertyInfo: typeof(Table6).GetProperty("column40", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Table6).GetField("<column40>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            column40.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var column41 = runtimeEntityType.AddProperty(
                "column41",
                typeof(string),
                propertyInfo: typeof(Table6).GetProperty("column41", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Table6).GetField("<column41>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            column41.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var column42 = runtimeEntityType.AddProperty(
                "column42",
                typeof(string),
                propertyInfo: typeof(Table6).GetProperty("column42", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Table6).GetField("<column42>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            column42.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var column43 = runtimeEntityType.AddProperty(
                "column43",
                typeof(string),
                propertyInfo: typeof(Table6).GetProperty("column43", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Table6).GetField("<column43>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            column43.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var column44 = runtimeEntityType.AddProperty(
                "column44",
                typeof(string),
                propertyInfo: typeof(Table6).GetProperty("column44", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Table6).GetField("<column44>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            column44.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var column45 = runtimeEntityType.AddProperty(
                "column45",
                typeof(string),
                propertyInfo: typeof(Table6).GetProperty("column45", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Table6).GetField("<column45>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            column45.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var column46 = runtimeEntityType.AddProperty(
                "column46",
                typeof(string),
                propertyInfo: typeof(Table6).GetProperty("column46", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Table6).GetField("<column46>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            column46.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var column47 = runtimeEntityType.AddProperty(
                "column47",
                typeof(string),
                propertyInfo: typeof(Table6).GetProperty("column47", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Table6).GetField("<column47>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            column47.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var column48 = runtimeEntityType.AddProperty(
                "column48",
                typeof(string),
                propertyInfo: typeof(Table6).GetProperty("column48", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Table6).GetField("<column48>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            column48.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var column49 = runtimeEntityType.AddProperty(
                "column49",
                typeof(string),
                propertyInfo: typeof(Table6).GetProperty("column49", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Table6).GetField("<column49>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            column49.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var column5 = runtimeEntityType.AddProperty(
                "column5",
                typeof(string),
                propertyInfo: typeof(Table6).GetProperty("column5", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Table6).GetField("<column5>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            column5.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var column6 = runtimeEntityType.AddProperty(
                "column6",
                typeof(string),
                propertyInfo: typeof(Table6).GetProperty("column6", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Table6).GetField("<column6>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            column6.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var column7 = runtimeEntityType.AddProperty(
                "column7",
                typeof(string),
                propertyInfo: typeof(Table6).GetProperty("column7", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Table6).GetField("<column7>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            column7.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var column8 = runtimeEntityType.AddProperty(
                "column8",
                typeof(string),
                propertyInfo: typeof(Table6).GetProperty("column8", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Table6).GetField("<column8>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            column8.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var column9 = runtimeEntityType.AddProperty(
                "column9",
                typeof(string),
                propertyInfo: typeof(Table6).GetProperty("column9", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Table6).GetField("<column9>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            column9.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "Table6");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
